version: '3.7'

services:
    php:
        image: pe100php
        volumes:
            - ./app/:/var/www/html/:cached
        ports:
            - 80:80
    db:
        image: mysql/mysql-server:5.5
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'oxid'
            MYSQL_USER: 'oxid'
            MYSQL_PASSWORD: "oxid"
            MYSQL_ROOT_PASSWORD: "oxid"
            MYSQL_ROOT_HOST: "%"
        volumes:
            - ./mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080